/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;


import br.com.ifba.curso.controler.CursoIControler;
import br.com.ifba.curso.view.utils.BntEditor;
import br.com.ifba.curso.view.utils.BntRenderer;
import br.com.ifba.curso.entity.Curso;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import br.com.ifba.curso.view.CadastrarCurso;
import jakarta.annotation.PostConstruct;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Component;



/**
 *
 * @author paulo
 */
@Component
public class ListarCurso extends javax.swing.JFrame {
    
    @Autowired
    private CursoIControler cursoControler;
    @Autowired
    private ApplicationContext context;

    /**
     * Creates new form CursoListar
     */
    public ListarCurso() {
        initComponents();
        
        setLocationRelativeTo(null);
    }
    
    @PostConstruct
    public void iniciar(){
        configurarTabela();
        loadTableCursos();
    }
    
    private void configurarTabela(){
        final int colunaEditar = 3;
        final int colunaExcluir = 4;
        
        BntRenderer bntRendererEditar = context.getBean(BntRenderer.class);
        bntRendererEditar.setLable("Editar");
        
        BntEditor bntEditorEditar = context.getBean(BntEditor.class);
        bntEditorEditar.setLable(tblCursos, "Editar");
        
        tblCursos.getColumnModel().getColumn(colunaEditar).setCellRenderer(bntRendererEditar);
        tblCursos.getColumnModel().getColumn(colunaEditar).setCellEditor(bntEditorEditar);
        
        
        BntRenderer bntRendererRemover = context.getBean(BntRenderer.class);
        bntRendererRemover.setLable("Remover");
        
        BntEditor bntEditorRemover = context.getBean(BntEditor.class);
        bntEditorRemover.setLable(tblCursos, "Remover");
        
        tblCursos.getColumnModel().getColumn(colunaExcluir).setCellRenderer(bntRendererRemover);
        tblCursos.getColumnModel().getColumn(colunaExcluir).setCellEditor(bntEditorRemover);
    }
    
    public final void loadTableCursos(){
        try {
            List<Curso> listaCursos = cursoControler.findAll();

            popularJTable(listaCursos);
        } catch (RuntimeException e){
            JOptionPane.showMessageDialog(this, e.getMessage(),"Erro",JOptionPane.WARNING_MESSAGE);
        }
    }
    
    public final void loadTableCursos(String pesquisa){
        try{
            List<Curso> listaCursos = cursoControler.findByCodigoCursoOrNome(pesquisa);

            popularJTable(listaCursos);
            
        } catch (RuntimeException e){
            JOptionPane.showMessageDialog(this, e.getMessage(),"Erro",JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private void popularJTable(List<Curso> cursos){
        DefaultTableModel modelo = (DefaultTableModel) tblCursos.getModel();
        modelo.setNumRows(0);
        
        for(Curso curso : cursos){
            modelo.addRow(new Object[]{
                curso.getCodigoCurso(),
                curso.getNome(),
                curso.isAtivo(),
                "Editar",
                "Remover"
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCursos = new javax.swing.JTable();
        lblListaCursos = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        bntPesquisar = new javax.swing.JButton();
        bntCadastrarNovo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Status", "Editar", "Remover"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCursos.setColumnSelectionAllowed(true);
        tblCursos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblCursos);
        tblCursos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblCursos.getColumnModel().getColumnCount() > 0) {
            tblCursos.getColumnModel().getColumn(0).setResizable(false);
            tblCursos.getColumnModel().getColumn(1).setResizable(false);
            tblCursos.getColumnModel().getColumn(2).setResizable(false);
            tblCursos.getColumnModel().getColumn(2).setPreferredWidth(5);
            tblCursos.getColumnModel().getColumn(3).setResizable(false);
            tblCursos.getColumnModel().getColumn(3).setPreferredWidth(5);
            tblCursos.getColumnModel().getColumn(4).setResizable(false);
            tblCursos.getColumnModel().getColumn(4).setPreferredWidth(5);
        }

        lblListaCursos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblListaCursos.setText("LISTA DE CURSOS");

        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });

        bntPesquisar.setText("Pesquisar");
        bntPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPesquisarActionPerformed(evt);
            }
        });

        bntCadastrarNovo.setText("Cadastrar Novo");
        bntCadastrarNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCadastrarNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 886, Short.MAX_VALUE)
                    .addComponent(lblListaCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntCadastrarNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblListaCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntPesquisar)
                    .addComponent(bntCadastrarNovo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        bntPesquisarActionPerformed(evt);
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void bntCadastrarNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCadastrarNovoActionPerformed
        
        CadastrarCurso viewCadastrarCurso = context.getBean(CadastrarCurso.class);
        viewCadastrarCurso.setLocationRelativeTo(this);
        viewCadastrarCurso.setVisible(true);
        this.loadTableCursos();
    }//GEN-LAST:event_bntCadastrarNovoActionPerformed

    private void bntPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPesquisarActionPerformed
        loadTableCursos(txtPesquisa.getText());
    }//GEN-LAST:event_bntPesquisarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCadastrarNovo;
    private javax.swing.JButton bntPesquisar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblListaCursos;
    private javax.swing.JTable tblCursos;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
