/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

import br.com.ifba.curso.view.aux.BntEditor;
import br.com.ifba.curso.view.aux.BntRenderer;
import br.com.ifba.curso.dao.CursoDao;
import br.com.ifba.curso.dao.CursoIDao;
import br.com.ifba.curso.entity.Curso;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import br.com.ifba.curso.view.CadastrarCurso;


/**
 *
 * @author paulo
 */
public class ListarCurso extends javax.swing.JFrame {

    /**
     * Creates new form CursoListar
     */
    public ListarCurso() {
        initComponents();
        
        final int colunaEditar = 3;
        final int colunaExcluir = 4;
        tblCursos.getColumnModel().getColumn(colunaEditar).setCellRenderer(new BntRenderer("Editar"));
        tblCursos.getColumnModel().getColumn(colunaEditar).setCellEditor(new BntEditor(tblCursos, "Editar"));
        
        tblCursos.getColumnModel().getColumn(colunaExcluir).setCellRenderer(new BntRenderer("Remover"));
        tblCursos.getColumnModel().getColumn(colunaExcluir).setCellEditor(new BntEditor(tblCursos, "Remover"));
        
        loadTableCursos();
        
        setLocationRelativeTo(null);
    }
    
    public final void loadTableCursos(){
        CursoIDao cursoDao = new CursoDao();
        List<Curso> listaCursos = cursoDao.findAll();
        
        System.out.println("Tamanho da lista encontrada: " + listaCursos.size());
        for (Curso c : listaCursos) {
            System.out.println("Curso encontrado: " + c.getNome());
        }

        popularJTable(listaCursos);
    }
    
    private void popularJTable(List<Curso> cursos){
        DefaultTableModel modelo = (DefaultTableModel) tblCursos.getModel();
        modelo.setNumRows(0);
        
        for(Curso curso : cursos){
            modelo.addRow(new Object[]{
                curso.getCodigoCurso(),
                curso.getNome(),
                curso.isAtivo(),
                "Editar",
                "Remover"
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCursos = new javax.swing.JTable();
        lblListaCursos = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        bntPesquisar = new javax.swing.JButton();
        bntCadastrarNovo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Status", "Editar", "Remover"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCursos.setColumnSelectionAllowed(true);
        tblCursos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblCursos);
        tblCursos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblCursos.getColumnModel().getColumnCount() > 0) {
            tblCursos.getColumnModel().getColumn(0).setResizable(false);
            tblCursos.getColumnModel().getColumn(1).setResizable(false);
            tblCursos.getColumnModel().getColumn(2).setResizable(false);
            tblCursos.getColumnModel().getColumn(2).setPreferredWidth(5);
            tblCursos.getColumnModel().getColumn(3).setResizable(false);
            tblCursos.getColumnModel().getColumn(3).setPreferredWidth(5);
            tblCursos.getColumnModel().getColumn(4).setResizable(false);
            tblCursos.getColumnModel().getColumn(4).setPreferredWidth(5);
        }

        lblListaCursos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblListaCursos.setText("LISTA DE CURSOS");

        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });

        bntPesquisar.setText("Pesquisar");

        bntCadastrarNovo.setText("Cadastrar Novo");
        bntCadastrarNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCadastrarNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 886, Short.MAX_VALUE)
                    .addComponent(lblListaCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntCadastrarNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblListaCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntPesquisar)
                    .addComponent(bntCadastrarNovo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void bntCadastrarNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCadastrarNovoActionPerformed
        CadastrarCurso viewCadastrarCurso = new CadastrarCurso(this, true);
        viewCadastrarCurso.setVisible(true);
        this.loadTableCursos();
    }//GEN-LAST:event_bntCadastrarNovoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ListarCurso().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCadastrarNovo;
    private javax.swing.JButton bntPesquisar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblListaCursos;
    private javax.swing.JTable tblCursos;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
